name: Generate Trophies
on:
  schedule: # Atualiza a cada 24 horas
    - cron: "0 0 * * *"
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Almir-git-unifc
          template: classic
          base: "" # Ignora a base padrão
          plugin_introduction: yes
          plugin_isocalendar: yes
          # Configuração dos troféus (badges)
          plugin_achievements: yes
          plugin_achievements_threshold: C # Exibe troféus de rank C para cima
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed
