name: Generate Stats SVG

on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats SVG
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Almir-git-unifc
          template: classic
          base: header, activity, community, repositories, metadata
          # Configurações de Cores Neon e Estilo
          config_timezone: America/Sao_Paulo
          filename: github-stats.svg
          config_colors: |
            {
              "border": "#808080",
              "text": "#39FF14",
              "title": "#39FF14",
              "icons": "#00FFFF"
            }
          # Filtros para bater com seu pedido
          queries: |
            {
              "rank": "B"
            }
